### PR TITLE
Bugs which require someone to fix things

### PR DESCRIPTION
**Pull request by jsoref**
This pull request will grow with things that need someone to actually work on fixing.

I'm going to write my comments as well, HTML...

### CODE REVIEW

**Comment by jsoref** [comment]
Earlier comments can be seen in:
https://github.com/jsoref/mediacapture-main/commits/pr_49_1
https://github.com/jsoref/mediacapture-main/commits/pr_49_2
https://github.com/jsoref/mediacapture-main/commits/pr_49_3
https://github.com/jsoref/mediacapture-main/commits/pr_49_4

**Comment by adam-be** [comment]
@jsoref, can you do an other iteration of this PR please.

**Comment by fluffy** [comment]
This is on josh's todo list

**Comment by alvestrand** [comment]
For the outstanding bugs, we are asking for separate pull requests.

**Pull request closed without merging**
