### PR TITLE
Define "camera" and "microphone" powerful feature types and algorithms

### PR DESCRIPTION
**Pull request by miketaylr**
See also https://github.com/w3c/mediacapture-output/pull/128

***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/mediacapture-main/pull/829.html" title="Last updated on Nov 18, 2021, 10:49 PM UTC (4fe103a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/829/b87662a...miketaylr:4fe103a.html" title="Last updated on Nov 18, 2021, 10:49 PM UTC (4fe103a)">Diff</a>

### CODE REVIEW

**Comment by miketaylr** [comment]
https://github.com/w3c/permissions/pull/324 is the related PR which removes the IDL from permissions.

**Review by dontcallmedom — APPROVED** [review]

**Comment by miketaylr** [comment]
Thanks @dontcallmedom, feel free to merge.

**Review by jan-ivar — APPROVED** [review]
We missed this one in the editor's meeting today.

I've verified this matches what was removed in w3c/permissions#324 verbatim, so I'm marking it editorial, and will merge it to unblock other PRs (respec errors on missing 'deviceId').

**Comment by miketaylr** [comment]
thanks!

**Pull request merged**
