### PR TITLE
Add an algorithm to determine whether a document is capturing or not.

### PR DESCRIPTION
**Pull request by youennf**
A document is said to be capturing if one of its track source is a capture source and is live.
A capture source is created either by getUserMedia or getDisplayMedia.

Fixes https://github.com/w3c/mediacapture-main/issues/887

***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/890.html" title="Last updated on Aug 18, 2022, 2:50 PM UTC (e86e63f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/890/7b093a3...youennf:e86e63f.html" title="Last updated on Aug 18, 2022, 2:50 PM UTC (e86e63f)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
The current algorithm is implemented so that the capturing state will return true for documents for which there is a privacy indicator. This, in particular, has an impact in case of transferred track.

**Comment by alvestrand** [comment]
This seems OK to me - but I'd like to understand where the linkage will be - this will return true both for camera and screen capture, I think.

**Comment by youennf** [comment]
> this will return true both for camera and screen capture, I think.

Right, or microphone.

**Comment by alvestrand** [comment]
Editors meeting: need to have answers to questions, but otherwise seems uncontroversial.

**Comment by youennf** [comment]
This will be used by https://github.com/WICG/compute-pressure/issues/82.

**Comment by kenchris** [comment]
Awesome, thanks all

**Pull request merged**
