### PR TITLE
Replace one png image with an svg

### PR DESCRIPTION
**Pull request by adam-be**
Proposed way to solve issue #361.

### CODE REVIEW

**Comment by adam-be** [comment]
Rendered preview: http://rawgit.com/adam-be/mediacapture-main/svg-images/getusermedia.html#the-model-sources-sinks-constraints-and-settings

**Comment by dontcallmedom** [comment]
@adam-be to make Travis happy, you need to update the W3CTRMANIFEST file with the new filename

**Comment by adam-be** [comment]
@dontcallmedom, OK thanks. @burnburn sent me the original slide set for these images so I will make SVGs out of those.

**Comment by adam-be** [comment]
Replaced by PR #365

**Pull request closed without merging**
