### PR TITLE
avoid MUST for non-UA requirement in SelectSettings definition.

### PR DESCRIPTION
**Pull request by jan-ivar**

### CODE REVIEW

**Comment by burnburn** [comment]
Yes, I believe that enforcement of providing a value here is already handled by the syntax itself.  Harald, Adam, can you please confirm?

**Comment by alvestrand** [comment]
I don't think this matters either way, but I think the requirement actually does something. I don't think the syntax enforces that you can't write 'height: {}' (empty dictionary).

**Comment by fluffy** [comment]
don't care one way or the other

**Comment by alvestrand** [comment]
No, we won't integrate this.

**Comment by jan-ivar** [comment]
"Each constraint MUST specify one or more values," or else what? Throw? Please explain.

**Comment by alvestrand** [comment]
That's a bug waiting to be filed - the action to be taken on constraints { height: {} } needs to be clear from the spec. Filed #139.

**Pull request closed without merging**
