### PR TITLE
define fitness distance when ideal is not specified

### LINKED ISSUE #125: What's the fitness distance if no ideal is specified?
I assume 0 but I couldn't find any text on this.

### PR DESCRIPTION
**Pull request by dontcallmedom**
close #125

### CODE REVIEW

**Comment by dontcallmedom** [comment]
I think my latest commit makes it clear that each set is a bailing step, and that the value obtained is the fitness distance; I don't think making the formula use `!ideal` makes the algorithm clearer, so I'd rather keep the prose description.
(as for the line break / word-wrap, it's independent of my PR :)

**Comment by stefhak** [comment]
LGTM.

**Comment by burnburn** [comment]
LGTM

**Comment by alvestrand** [comment]
LGTM.

**Pull request merged**
