### PR TITLE
Fix Not Found Error in gUM algorithm

### PR DESCRIPTION
**Pull request by burnburn**
It appears that the rewrite of the gUM algorithm to use SelectSettings inadvertently changed some of the errors.  Specifically, the NotFoundError should have been for the case where no suitable sources were available even before applying constraints, and the ConstraintNotSatisfiedError should have been used for the case where no suitable sources were found after applying constraints, meaning that at least one required constraint could not be satisfied.

### CODE REVIEW

**Comment by jan-ivar** [comment]
Doh! And thus constraint failure in Firefox fails with NotFoundError. :/ Good catch.

**Comment by stefhak** [comment]
Yes, good catch. We should just merge this IMO.

**Comment by burnburn** [comment]
Okay, I am merging.  Now for another attempt at merging #194 :)

**Comment by stpeter** [comment]
Belated +1 - I looked at this earlier but neglected to reply. :(

**Pull request merged**
