### PR TITLE
short descriptions of arguments to callbacks in callback-based gUM

### PR DESCRIPTION
**Pull request by dontcallmedom**

### CODE REVIEW

**Comment by alvestrand** [comment]
Looks good to me.

**Comment by burnburn** [comment]
These should refer to navigator.getUserMedia() rather than navigator.mediaDevices.getUserMedia() since these are only applicable to the callback version of the API.  Otherwise, thanks for filling these in :)

**Comment by dontcallmedom** [comment]
@burnburn I've used mediaDevices references on purpose — that's where the algorithms are defined nowadays.

**Comment by alvestrand** [comment]
After talking to Dan, I think he's right. We need to point to navigator.getUserMedia for the procedure, because that's where we define what the argument for the callback is - the mediaDevices.getUserMedia definition talks about resolving a promise.

**Comment by dontcallmedom** [comment]
ok, will update

**Pull request merged**
