### PR TITLE
Clarify that some device ids may not be origin-unique

### PR DESCRIPTION
**Pull request by youennf**
Also refactor to make reference from deviceId/groupId constraints to MediaDeviceInfo attribute fields.
Clarify groupId lifetime.
Make reference to rfc4122 for deviceId.

### CODE REVIEW

**Comment by youennf** [comment]
Covers https://github.com/w3c/mediacapture-main/issues/551

**Comment by alvestrand** [comment]
Youenn will split this into a PR that strictly deals with "empty string" and another PR for the refactoring stuff that is also in here.

**Comment by youennf** [comment]
I split PR in sub PRs: https://github.com/w3c/mediacapture-main/pull/591, https://github.com/w3c/mediacapture-main/pull/590 and https://github.com/w3c/mediacapture-main/pull/589.
I rebased this PR on top of the other PRs.
I'll file another PR specifically dedicated to empty string semantics.

**Comment by youennf** [comment]
> I'll file another PR specifically dedicated to empty string semantics.

This is https://github.com/w3c/mediacapture-main/pull/595

**Pull request merged**
