### PR TITLE
Reformat with enforced line wrap at 80

### PR DESCRIPTION
**Pull request by dontcallmedom**
When this is merged, Travis CI will complain on pull requests that aren't line-wrapped at 80 characters.

To do proper line-wrapping, this idea is to:
* commit your changes without line-wrap
* rewrap the content using webrtc-respec-ci/Makefile with `make linewrap LINEWRAPLENGTH=80`
* do a commit for the linewrap

### CODE REVIEW

**Comment by alvestrand** [comment]
Land it when you can...

**Comment by dontcallmedom** [comment]
I'd rather do it when the list of pull requests empties, otherwise, there will lots of painful rebasing.

**Comment by martinthomson** [comment]
@dontcallmedom, can we just have a simple `make linewrap` command (or even `make wrap`) without the extra argument?

**Comment by alvestrand** [comment]
The "tidy-test" target in the repo's Makefile is one year old today. Perhaps someone could tweak it?

**Pull request merged**
