### PR TITLE
remove DOMExceptions from error names table

### PR DESCRIPTION
**Pull request by burnburn**
Now that updates to the error names have been completed, can we just remove all the ones from this table that are actually DOMExceptions?

### CODE REVIEW

**Comment by burnburn** [comment]
Posted to list for review and comment.

**Comment by stefhak** [comment]
I think we should follow Anne's advice and remove the ones that are DOMExceptions.

**Comment by stpeter** [comment]
Here is proposed text to place before the table:

      <p class="note">There is a known issue with this table of error names,
      because <code>MediaStreamError</code> has been removed but is still 
      needed in the legacy, callback-based getUserMedia interface.  This issue 
      will be fixed through resolution of <a 
      href="https://github.com/w3c/mediacapture-main/pull/216">PR #216</a>.
      </p>

**Comment by stefhak** [comment]
That text LGTM.

**Comment by burnburn** [comment]
@stpeter, please go ahead and add the text and merge the PR (or the other order, if that's easier.)

**Comment by burnburn** [comment]
Looks like Peter's out, so I'll apply the change Peter suggests and merge this PR.

**Pull request merged**
