### PR TITLE
Distinguish between links to the active attribute and the active/inactive concept (Issue #159)

### PR DESCRIPTION
**Pull request by adam-be**

### CODE REVIEW

**Comment by fluffy** [comment]
LGTM

**Comment by adam-be** [comment]
Modifying the public API attribute here is might not be what we want.

Actually, I don't think we need to say anything about the "active" state when we construct the MediaStream since the state is indirectly defined by the stream's tracks.

"
A MediaStream object is said to be active when it has at least one MediaStreamTrack that has not ended. A MediaStream that does not have any tracks or only has tracks that are ended is inactive.
"

**Comment by alvestrand** [comment]
What's the proper idiom for describing "this looks like an attribute, but is actually the result of a computation over the underlying state of the object's constituent parts"?

**Comment by annevk** [comment]
If active/inactive are the result of something else, you don't need to modify the attribute. IDL attributes are getter/setter pairs when you get to JavaScript. I've started defining them as such, e.g.:

"The active attribute's getter must return true if the context object's is active, and false otherwise."

Given that active/inactive are the result of a computation, you don't need to explicitly set either those or the active attribute in the constructor as @adam-be observes.

**Comment by adam-be** [comment]
Updated to reflect recent discussion.

**Pull request merged**
