### PR TITLE
defer to HTML5.1 for direct assignment

### PR DESCRIPTION
**Pull request by dontcallmedom**
per #161

### CODE REVIEW

**Comment by alvestrand** [comment]
The reference as given is to a nightly build.
There's a WD link possible:

http://www.w3.org/TR/2015/WD-html51-20150417/semantics.html#location-of-the-media-resource

Should we use that (or the undated equivalent) instead?

Also, the pointed-to text is shorter than our text - someone needs to verify that all the text is actually present. @JimBarnett tagged?

**Comment by dontcallmedom** [comment]
I think the nightly draft is OK, but if there is a preference for a more stable draft, I'm happy to update the PR — let me know.

The text is shorter, but the algorithm to load and play media resources includes the stuff about MediaProvider; what I haven't found the time to check is whether the mapping between attributes values and MediaStream specificities has been reproduced in the prose.

**Comment by JimBarnett** [comment]
Dom,
   I looked at the PR, and it looks to me like some of the details about 
the relationship between the MediaStream and the corresponding HTML 
elements are missing.For example, the removed text includes statements 
like:

"For each MediaStreamTrack in the MediaStream , including those that are 
added after the User Agent enters the media element load algorithm, the 
User Agent MUST create a corresponding AudioTrack or VideoTrack as 
defined in [HTML5]. Since the order in the MediaStream 's track set is 
undefined, no requirements are put how the AudioTrackList and 
VideoTrackList are ordered.

The properties of the AudioTrack and VideoTrack objects MUST be 
initialized as follows. Let

AudioTrack.id and VideoTrack.id have the value of the corresponding 
MediaStreamTrack.id attribute
AudioTrack.kind and VideoTrack.kind be "main"
AudioTrack.label and VideoTrack.label have the value of the 
corresponding MediaStreamTrack.label attribute
AudioTrack.language and VideoTrack.language be the empty string"

I don't find anything like that in the HTML text.Perhaps the authors 
have decided that these details fall out from more general statements 
elsewhere in the spec, or they want to leave them up to the 
implementation.It's fine with me if that's the result of a conscious 
decision, but as it stands the text does not specify things to the level 
of detail that the Media Capture group thought was necessary.

- Jim

**Comment by dontcallmedom** [comment]
@JimBarnett the requirement to update the audio/video track lists when a MediaStream is updated is covered by the following text:
> Whenever new data for the current media resource becomes available, queue a task to run the first appropriate steps from the [media data processing steps](http://www.w3.org/TR/2015/WD-html51-20150417/semantics.html#media-data-processing-steps-list) list below.

in the mode "local" of the [resource fetch algorithm](http://www.w3.org/TR/2015/WD-html51-20150417/semantics.html#concept-media-load-resource)

I haven't found any text that deals with setting of id, kind and label attributes to the MediaStreamTrack values — that should probably be filed as a bug on the HTML spec.

**Comment by stefhak** [comment]
I assume the setting if id, kind and label is implicit in the step "Create an Audio/VideoTrack object to represent the audio/video track.", but I think it should be explicit that the id, label and kind is inherited for the MediaStreamTrack, so +1 for filing a bug on HTML spec

**Comment by alvestrand** [comment]
Closing - replaced by #171

**Pull request closed without merging**
