### PR TITLE
typedef MediaStreamError as an object

### PR DESCRIPTION
**Pull request by jan-ivar**
From discussion in https://github.com/w3c/mediacapture-main/pull/216. I don't have any better ideas than this.

### CODE REVIEW

**Comment by jan-ivar** [comment]
I matched the `OverConstrainedError` link to the existing use. Should they perhaps both link to [7.2](https://rawgit.com/w3c/mediacapture-main/8464a1db1f4beee6495e5ca8add81ad33a71a35f/getusermedia.html#overconstrainederror-object) instead?

**Comment by burnburn** [comment]
Overall this looks good.  I need to check into which OverconstrainedError link to use at this point given other PRs but will do that.

**Comment by burnburn** [comment]
Yes, it should link to 7.2 instead.  I believe the reference is #overconstrainederror-object.

**Comment by jan-ivar** [comment]
There were a lot of links. Trying this instead.

**Pull request merged**
