### PR TITLE
Answer TAG self-review privacy/security questionnaire

### PR DESCRIPTION
**Pull request by dontcallmedom**
Needs review; there is in particular a "TBD" for the incognito mode

### CODE REVIEW

**Comment by ekr** [comment]
I'm not sure that this is a particularly helpful format. Is this section mandatory?

**Comment by dontcallmedom** [comment]
I copied the format that was used in the [CSS Basic UI module](https://drafts.csswg.org/css-ui-3/#security-privacy-considerations) as suggested in the initial issue #212 

The section is not mandatory at this point, and maybe if having reviewed the questions and answers, we distil it into the privacy & security considerations section, we'll be ok.

**Comment by ekr** [comment]
In that case, I suggest putting this into an issue, not a PR.

**Comment by stpeter** [comment]
@dontcallmedom I agree that distilling this into the privacy & security considerations would be preferable and I'd be happy to do that.

@ekr We do have an issue for this: https://github.com/w3c/mediacapture-main/issues/212

**Comment by alvestrand** [comment]
Closing; @stpeter will work out a security considerations change that includes the information as response to #212.

**Pull request closed without merging**
